my_controller:
  type: "my_franka_controller/MyController"
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

/panda/motion_generators/position/gains:
  panda_joint1: { p: 100, i: 0, d: 0 }
  panda_joint2: { p: 100, i: 0, d: 0 }
  panda_joint3: { p: 100, i: 0, d: 0 }
  panda_joint4: { p: 100, i: 0, d: 0 }
  panda_joint5: { p: 50, i: 0, d: 0 }
  panda_joint6: { p: 50, i: 0, d: 0 }
  panda_joint7: { p: 25, i: 0, d: 0 }

/panda/motion_generators/velocity/gains:
  panda_joint1: { p: 30, i: 0, d: 0 }
  panda_joint2: { p: 30, i: 0, d: 0 }
  panda_joint3: { p: 30, i: 0, d: 0 }
  panda_joint4: { p: 30, i: 0, d: 0 }
  panda_joint5: { p: 10, i: 0, d: 0 }
  panda_joint6: { p: 10, i: 0, d: 0 }
  panda_joint7: { p: 5, i: 0, d: 0 }


